name: Code Review

on: [push, pull_request]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OpenAI ChatGPT Code Review
        uses: adshao/chatgpt-code-review-action@v0.2
        with:
          PROGRAMMING_LANGUAGE: 'JavaScript'
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          FULL_REVIEW_COMMENT: 'chatgpt'
          REVIEW_COMMENT_PREFIX: 'chatgpt:'
